{
  "formatVersion": "1.1",
  "component": {
    "group": "com.guardsquare",
    "module": "dexguard-gradle-plugin",
    "version": "9.4.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "dexguard-gradle-plugin-9.4.16.jar",
          "url": "dexguard-gradle-plugin-9.4.16.jar",
          "size": 332602,
          "sha512": "7649c68b639034d7b0c74b01108c7b73b6b0b9f519cf7cc51bc36063cfa30ec295501dd8ffd3e4afff7bf517501fcfd3e72ab25f89c247880ef93bdef91bfe0e",
          "sha256": "5cf5582e69a569ba54ba51b0da0df49957ee65c6cb2ca2766de878b4501376eb",
          "sha1": "e0f944e3e141e7bf77e6d265dea281ede5cd09ed",
          "md5": "ba3377a9788e08e43746b241dac3f81c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.0"
          }
        }
      ],
      "files": [
        {
          "name": "dexguard-gradle-plugin-9.4.16.jar",
          "url": "dexguard-gradle-plugin-9.4.16.jar",
          "size": 332602,
          "sha512": "7649c68b639034d7b0c74b01108c7b73b6b0b9f519cf7cc51bc36063cfa30ec295501dd8ffd3e4afff7bf517501fcfd3e72ab25f89c247880ef93bdef91bfe0e",
          "sha256": "5cf5582e69a569ba54ba51b0da0df49957ee65c6cb2ca2766de878b4501376eb",
          "sha1": "e0f944e3e141e7bf77e6d265dea281ede5cd09ed",
          "md5": "ba3377a9788e08e43746b241dac3f81c"
        }
      ]
    }
  ]
}
